config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :count
    end
    member do
      get :name
    end
    resources :shops
  end  
  root 'users#index'
  resources :entries, defaults: { format: 'json' }

end

app/models/shop.rb
class Shop
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  field :firstname, type: String
  field :lastname, type: String
  field :age, type: Integer
  field :gender, type: String
  field :created_at, type: Time, default: Time.now
  field :updated_at, type: Time, default: Time.now
  validates_presence_of :firstname,:lastname,message: "必填!"
  validates_numericality_of :age, greater_than: 0
  validates_inclusion_of :gender, in: ["Male", "Female","Others"],message: "必須為 Male or Female or Others"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :name]
  before_action :params_permit,only: [:address]
  # GET /users.json
  def index
    @users = User.all    
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new    
    @user = User.new
  end
  #use post
  def count            
    @usercounts = User.all.count
    respond_to do |format|      
      format.json { render json: @usercounts}
    end           
  end
  
  def name
        respond_to do |format|       
        format.html { render :name }
        format.json { render json: @user }
    end  
  end
  # GET /users/1/edit
  def edit        
      respond_to do |format|       
        format.html { render :edit }
        format.json { render json: @user }
    end  
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def params_permit
    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname,:lastname,:age,:gender,address: [:country,:address_1,:address_2])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Onboard</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body ng-app="application_body">  
    <%= yield %> 
</body>
</html>

app/views/users/_form.html.erb
<style>
.formsubmit{
      border-color: rgb(216, 216, 216) rgb(209, 209, 209) rgb(186, 186, 186);
}
</style>

<%= simple_form_for user, html: { name: 'form','ng-controller': 'validateCtrl' } do |f| %>  
  <div class="form-group">
    <%= f.input :firstname,label: false,required: true ,placeholder: "姓", input_html: {'ng-model': 'firstname'} %>
     <span style="color:red" ng-show="hasError('firstname')">姓必填。</span>    
    <%= f.input :lastname,label: false,required: true  ,placeholder: "名",input_html: {'ng-model': 'lastname'} %>
    <span style="color:red" ng-show="hasError('lastname')">名必填。</span>
    <%= f.input :age ,label: false,placeholder: "20" ,required: true , input_html: {'ng-model': 'age',type: 'number'} %>    
    <span style="color:red" ng-show="onlyNumber('age')">年齡必填。(只能輸入數字)</span>
    <%= f.input :gender,label: false,as: :select, include_blank: false, include_hidden: true ,collection: [['Male', 'Male'], ['Female', 'Female'],['Others','Others'] ],required: true , input_html: {'ng-model': 'gender'} %>    
    <span style="color:red" ng-show="gendervalidagtes('gender')">請選擇性別。</span>    
  </div>
  <div class="actions">
    <%= f.button :submit,'ng-disabled': "validatesformsubmit();",class: 'formsubmit' %>
  </div>
<% end %>

app/views/users/count.html.erb
<span>Total</span>  
<%= @usercounts %> Member

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> 

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<div ng-controller = "index_user_data as settings">
<table class="col-md-12">
  <thead>
    <tr>
      <th class="col-md-2">First Name</th>
      <th class="col-md-2">Last Name</th>
      <th class="col-md-2">Age</th>
      <th class="col-md-2">Gender</th>
      <th colspan="4" class="col-md-4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="col-md-2"><%= user.firstname %></td>
        <td class="col-md-2"><%= user.lastname %></td>
        <td class="col-md-2"><%= user.age %></td>
        <td class="col-md-2"><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="JavaScript:void(0);" ng-click="newview=false;editview=true;get_user_data('<%= user.id %>')" >Angular Edit User</a></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
  
  <a href="JavaScript:void(0);" ng-click="newview=true;editview=false;" >New User</a>
  <div>
    <span>Total</span>  
    {{usercount}} Member
  </div>
  <div ng-show="newview" class="view-animate-container "style="width: 250px;">
  <div new-user class="view-animate"></div>  
  </div>
  <div ng-show="editview" class="view-animate-container "style="width: 250px;">    
  <div  ng-include="template" class="view-animate"></div>    
  </div>
</div>

app/views/users/name.html.erb
Firstname
<%= @user.firstname %>
Lastname
<%= @user.lastname %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Show</h1>

<table class="col-md-12">
  <thead>
    <tr>
      <th class="col-md-2">First Name</th>
      <th class="col-md-2">Last Name</th>      
      <th class="col-md-2">Age</th>
      <th class="col-md-2">Gender</th>    
    </tr>
  </thead>
  <tbody>    
      <tr>
        <td class="col-md-2"><%= @user.firstname %></td>
        <td class="col-md-2"><%= @user.lastname %></td>
        <td class="col-md-2"><%= @user.age %></td>
        <td class="col-md-2"><%= @user.gender %></td>
      </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>